version: "2"
run:
  timeout: 5m
  concurrency: 4
  go: "1.24"

linters:
  default: none
  enable:
    - bodyclose
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - dupl
          - gosec

