name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: ko-build/setup-ko@v0.6
      - run: |
          echo "${{ secrets.PACKAGES_TOKEN }}" | ko login ghcr.io --username "${{ secrets.PACKAGES_USER }}" --password-stdin

          ko publish --bare ./
        env:
          GITHUB_TOKEN: ${ secrets.PACKAGES_TOKEN }
          KO_DOCKER_REPO: ghcr.io/carto-run/fake-jenkins # Setting this forces ko to skip the default login 
