name: Publish

on:
  push:
    branches: ['main']
  pull_request: # FIXME this needs to be removed before merging

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3

      - uses: imjasonh/setup-ko@v0.6
      - run: |
          echo "${{ secrets.PACKAGES_TOKEN }}" | ko login ghcr.io --username "dummy" --password-stdin

          ko publish --bare ./
        env:
          GITHUB_TOKEN: ${ secrets.PACKAGES_TOKEN }
          KO_DOCKER_REPO: ghcr.io/carto-run/fake-jenkins
