name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: ['main']

  workflow_dispatch: {}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: ko-build/setup-ko@v0.9
        env:
          KO_DOCKER_REPO: ghcr.io/carto-run/fake-jenkins # Setting this forces ko to skip the default login

      - name: ko publish
        env:
          auth_token: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo "${auth_token}" | ko login ghcr.io --username "user" --password-stdin

          ko publish --bare ./

