name: Publish

on:
  push:
    branches: ['main']
  pull_request: # FIXME this needs to be removed before merging

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.6
      - run: ko publish --bare ./
        env:
          GITHUB_TOKEN: ${ secrets.PACKAGES_TOKEN }
