name: woke
on:
  - pull_request
jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
          woke-args: -c https://vmw-its-woke-client-rules-resources-stg.s3.us-west-2.amazonaws.com/its-woke-rules.yaml .
